### PR TITLE
Job deployed to nats connects to nats on own IP

### PR DESCRIPTION
**Pull request by mcwumbly**
During upgrades, if previous deployment does not have nats-tls or the
metrics-discovery-registrar job at all, deployment can fail because
nats.service.cf.internal does not return any healthy instances to
connect that also have nats-tls running.

The first nats intance to deploy that would have that job running is not
healthy until the metrics-discovery-registrar is running. But
metrics-discovery-registrar has no nats-tls job it can resolve with
bosh-dns because the only instance that has nats-tls running is the
same, first nats instance. But that instance isn't healthy yet because
the metrics-discovery-registrar job isn't running yet... you get the
idea.

One way around this is to change the bosh-dns-aliases query from "*" to
"q-s4". But that means anyone locating nats will get unhealthy instances
in the mix. That may be acceptable given how nats clients retry
connections. But this change is more localized and addresses the root
cause more directly.

With this change, when nats_instance_group is configured, the
metrics-discovery-registrar jobs that get deployed to the instance group
of that name will connect to the nats job running on the same VM by IP
address instead of using bosh-dns to find a random instance. The new
property has no default, so if it is not set, the current behavior is
preserved.

### CODE REVIEW

**Comment by mcwumbly** [comment]
Just realized that we probably need/want to make the name used for comparison in the conditional a variable spec property that _defaults_ to "nats". That would allow it to be overridden on deployments that use a different instance group name or different colocation strategy.

**Comment by mcwumbly** [comment]
OK, PR has been updated with a new spec property `nats_instance_group`. There is no default for the new property, and if not set, the current behavior is preserved. Deployments can choose to set this property to the value of the instance group name they use in their deployment for running nats-tls if they have a need to do so.

**Comment by heycait** [comment]
> One way around this is to change the bosh-dns-aliases query from "*" to
"q-s4". But that means anyone locating nats will get unhealthy instances
in the mix. That may be acceptable given how nats clients retry
connections. But this change is more localized and addresses the root
cause more directly.

**Comment by heycait** [comment]
> One way around this is to change the bosh-dns-aliases query from "*" to
"q-s4". But that means anyone locating nats will get unhealthy instances
in the mix. That may be acceptable given how nats clients retry
connections. But this change is more localized and addresses the root
cause more directly.

**Comment by mcwumbly** [comment]
> What about "q-s3" for only healthy instances? Looked at TAS for inspiration and every other bosh dns alias uses "*". Would there be any issue to just changing this reach only healthy instances?

`q-s3` would suffer from the same problem. The issue is that during this time in the deployment, the only instance that has the nats-tls job is unhealthy. The other instances are healthy, but do not yet have the nats-tls job, because they haven't rolled yet.


> Is spec.ip the external or internal IP of the VM?

It's the IP address you see with `bosh vms`. It is reachable at that address from other VMs on the same network.

> Does this mean that if the NATs TLS job on the VM went down, this would stop working?

The metrics-discovery-registrar job _on that VM_ would stop working while nats-tls on that VM is unavailable.

> How were you able to test these changes in an upgrade since it doesn't always fail?

The failure is 100% reproducible in the case where:
* You are upgrading from a deployment that does not contain the metrics-discovery-registrar job
* You are upgrading to a version that includes the job and connects to nats-tls
* You have more than one nats instance

**Comment by heycait** [comment]
Can you elaborate on how NATs work when there are multiple instances?

**Comment by mcwumbly** [comment]
> Can you elaborate on how NATs work when there are multiple instances?

That's a pretty broad question. I'm not sure I'm interpreting it properly, but here goes:

Let's assume this is `cf-deployment` and there are three nats instances in the nats instance group. Each of those instances is running the following jobs (and others, but let's call these out for now):
- `nats`
- `nats-tls`
- `metrics-discovery-registrar`

The `nats` and `nats-tls` jobs are configured as a "cluster" of 6 servers (2 processes on each instance). So each job connects with all 5 other jobs. Those connections _all_ use TLS. 

These servers also receive client connections from the following jobs:
- `metrics-discovery-registrar` connects to `nats-tls`(currently on any instance due to the `*` query)
- `route-emitter` on each `diego-cell` instance connects to `nats-tls` (on which ever instance it first connects to via the `* ` query)
- `gorouter` on the `router` instance group connects to the `nats` job

Messages that are published to any `nats` or `nats-tls` server get shared with the other members of the cluster, so any subscriber to any one of those jobs will receive those messages.  

So, if we change `metrics-discovery-registrar` on a nats instance to connect to the `nats-tls` job _on that instance_ instead of _any_ instance, it will still be able to publish to subscribers of any nats server in the cluster.

Does that answer your question? If not, can you be more specific?

**Comment by heycait** [comment]
Yes thanks! I'll chat with the team to see if there are any other questions, otherwise, I think we can merge this in.

**Comment by louis-brann** [comment]
So it turns out that we can't use IP to connect to nats-tls because then TLS SAN verification will fail and it will fall back to regular nats... and spike CPU and cause outages including expirations of internal routes? There's a big issue with that described in the nats-release repo: https://github.com/cloudfoundry/nats-release/issues/25. So this fix is not an option.

But why is the using the hostname failing? Looking at the cf-deployment manifest, the hostname [`nats.service.cf.internal` uses the `'*'` query](https://github.com/cloudfoundry/cf-deployment/blob/master/cf-deployment.yml#L320-L326). According to the [BOSH DNS documentation](https://bosh.io/docs/dns/#constructing-queries), the default is to check healthy and unchecked instances:
> s0 - Default - 'smart' strategy that returns healthy and unchecked instances; if there are no healthy or unchecked instances, all instances will be returned.

This means that using just the hostname will still fail if all instances are checked but unhealthy. 

According to the BOSH DNS documentation, our job should use BOSH links for this purpose (https://bosh.io/docs/dns/#consuming-dns-job-templates), and it looks like y’all already provide a `nats-tls` link, so we should just consume that.

Looking at the `nats-tls` custom provider definition, we may be able to refer to this with the `nats.hostname` property (https://github.com/cloudfoundry/nats-release/blob/develop/jobs/nats-tls/spec#L28).

Would you like to update this PR, or should we close it and make a different one?

**Comment by mcwumbly** [comment]
> So it turns out that we can't use IP to connect to nats-tls because then TLS SAN verification will fail.

Did you see that failure? When first working on this, I wasn't sure if connecting by IP would work, but I tried it and it did. So I went with that option for the sake of simplicity.  I thought perhaps the IP was in the SAN of the certificate... Perhaps it was doing something I didn't understand though?

Another option would be to append `spec.name` to `nats.service.cf.internal` so that it ends up as `some-instance-guid.nats.service.cf.internal`. I did validate that as well when testing this earlier and it should work. 

If you prefer that approach, I can update this PR accordingly.

**Comment by louis-brann** [comment]
Hi @mcwumbly,

Using `spec.id` makes sense to us. We tested it out locally, changing the `spec.ip` to `#{spec.id}.#{nats.hostname}` and saw it succeed. If you could update the PR accordingly (and as part of it, change the hardcoded default `nats_hostname` to retrieve it from the bosh link), that would be swell.

We haven't been able to reproduce the failure ourselves, but we have seen it in the field. When you tried connecting via IP and saw it succeed, did you still have the NATS TLS failover enabled? From our understanding, nats has a service discovery that would automatically detect other available hosts and would find a non-TLS host after failing the TLS host, and would still appear to work, just not over TLS (hence why using the IP might still work). Using the `spec.id` + hostname should match the cert and work with TLS.

Thanks
@louis-brann and @angelachin

**Comment by mcwumbly** [comment]
> When you tried connecting via IP and saw it succeed, did you still have the NATS TLS failover enabled?
I'm not sure about this configuration, but you must be right. On a `cf-deployment` with a single instance of `nats`, I just found the following:

## Summary

When the non-TLS `nats` job is not running, all of the following values for `env.NATS_HOSTS` in `/var/vcap/jobs/metrics-discovery-registrar/config/bpm.yml` fail with a certificate error:


* IP address
* ${instanceID}.nats.service.cf.internal
* nats.service.cf.internal

This fails because it cannot find any server:
* nats.default.cf.bosh

_Only_ this works:
* ${instanceID}.nats.default.cf.bosh

### Details

Here are the details showing the config lines used in each case above, and the error in `metrics-discovery-registrar.stderr.log`:

IP address:
```
NATS_HOSTS: nats://nats:$password@10.0.1.0:4224`
# 2020/10/20 16:27:01 Unable to connect to nats servers: x509: cannot validate certificate for 10.0.1.0 because it doesn't contain any IP SANs
```

${instanceID}.nats.service.cf.internal:
```
NATS_HOSTS: nats://nats:$password@ec21ab15-4d0c-4227-9ba4-f71ea7ee2312.nats.service.cf.internal:4224
# 2020/10/20 16:33:49 Unable to connect to nats servers: x509: certificate is valid for *.nats.default.cf.bosh, not ec21ab15-4d0c-4227-9ba4-f71ea7ee2312.nats.service.cf.internal
```

nats.service.cf.internal:
```
NATS_HOSTS: nats://nats:$password@nats.service.cf.internal:4224
# 2020/10/20 16:33:49 Unable to connect to nats servers: x509: certificate is valid for *.nats.default.cf.bosh, not nats.service.cf.internal
```

nats.default.cf.bosh:
```
NATS_HOSTS: nats://nats:$password@nats.default.cf.bosh:4224
# 2020/10/20 16:48:11 Unable to connect to nats servers: nats: no servers available for connection
```

${instanceID}.nats.default.cf.bosh:
```
NATS_HOSTS: nats://nats:$password@ec21ab15-4d0c-4227-9ba4-f71ea7ee2312.nats.default.cf.bosh:4224
# 2020/10/20 16:50:43 Metrics endpoint is listening on 127.0.0.1:15821
```

### Next steps

Maybe the certificate being generated for `nats-tls` is incorrect in the default `cf-deployment`? If so, that's probably something that needs to be addressed.

In the meantime, I'm going to update this PR as requested. I think ultimately it is the right change for this issue.

**Comment by davewalter** [comment]
@mcwumbly

> Maybe the certificate being generated for `nats-tls` is incorrect in the default `cf-deployment`? If so, that's probably something that needs to be addressed.

Do you have any ideas about how/why it might be wrong, and what it should be? We are about to cut v14 of cf-deployment to release the cert changes for NATS TLS, and would love to have confidence in the [changes we have made](https://github.com/cloudfoundry/cf-deployment/commit/cb9689a0adacf85baac98d5a8f900875a69bc6d8) before we do.

Based on your statement that only `${instanceID}.nats.default.cf.bosh` works, is it possible that the [BOSH DNS aliases defined in cf-deployment for NATS](https://github.com/cloudfoundry/cf-deployment/blob/8bf124a7182b151175246b662fd9bb9b66df0ce7/cf-deployment.yml#L321-L334) are wrong?

**Comment by mcwumbly** [comment]
@davewalter I'm not sure. I was just surprised to see this error in particular:

```
NATS_HOSTS: nats://nats:$password@nats.service.cf.internal:4224
# 2020/10/20 16:33:49 Unable to connect to nats servers: x509: certificate is valid for *.nats.default.cf.bosh, not nats.service.cf.internal
```

I haven't had time to do further debugging yet, and am only able to follow up on this issue part time at the moment. 

If you have time to look into it further, here are the minimal repro steps for the potential cert issue in cf-deployment:

1. Deploy `cf-deployment` with 1 instance of `nats`
2. Stop the `nats` job: `monit stop nats`
3. Restart `metrics-discovery-registrar`: `monit restart metrics-discovery-registrar`
4. Check the last line of `metrics-discovery-registrar.stderr.log` to see whether it connected successfully or failed with a certificate (or other) error.

Try the above before and after the change you made. The version I have deployed currently does _not_ include your change, so it's possible that your change is exactly what fixes this issue.

**Comment by mcwumbly** [comment]
@davewalter I just tested the above after applying your change, and now it works as expected for both of these cases:

* ${instanceID}.nats.service.cf.internal
* nats.service.cf.internal

@louis-brann and @angelachin - I think this is ready to merge now if it looks good to you.

**Comment by louis-brann** [comment]
sweet, thanks @mcwumbly and @davewalter!

**Pull request merged**
