### PR TITLE
Bump NATS

### PR DESCRIPTION
**Pull request by ctlong**
# Description

Bump `github.com/nats-io/nats-server/v2` to v2.7.4.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Testing performed?

- [ ] Unit tests
- [ ] Integration tests
- [ ] Acceptance tests

## Checklist:

- [x] This PR is being made against the `main` branch, or relevant version branch
- [ ] I have made corresponding changes to the documentation
- [ ] I have added testing for my changes

### CODE REVIEW

**Comment by mkocher** [comment]
Any idea why nats.go is on a git hash and not a released version?

**Comment by mkocher** [comment]
Any idea why nats.go is on a git hash and not a released version?

**Comment by ctlong** [comment]
Hmmm seems like the [NATS go client](https://github.com/nats-io/nats.go#installation) is well behind the [NATS server](https://github.com/nats-io/nats-server) for some reason.

If we decide to pin nats.go to its latest release (v1.13.0) for now then we're stuck with nats-server v2.6.2.

**Comment by Benjamintf1** [comment]
@ctlong sorry, Reimplemented this on main, should be fine now i believe.

**Pull request closed without merging**
